name: Generate charts

on:
  schedule:
    # every day at 4am
    - cron: "0 4 * * *"

jobs:
  update-prices:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "17"
          cache: "yarn"
          cache-dependency-path: |
            charts/yarn.lock

      - name: Yarn install
        working-directory: ./charts
        run: |
          yarn install --frozen-lockfile

      - name: Yarn build
        working-directory: ./charts
        run: |
          yarn build

      - name: Setup hledger
        run: |
          TMP_DIR=$(mktemp -d -t ci-XXXXXXXXXX)
          pushd "$TMP_DIR"
          curl -LO "https://github.com/simonmichael/hledger/releases/download/1.25/hledger-linux-x64.zip"
          unzip hledger-linux-x64.zip
          mkdir -p "$HOME/.local/bin"
          cp hledger-linux-x64 "$HOME/.local/bin/hledger"
          chmod +x "$HOME/.local/bin/hledger"
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Generate charts
        working-directory: ./charts
        run: |
          yarn generate

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update charts
